### ISSUE TITLE
Simplify the CSS code for other shared properties.

### ISSUE THREAD

**Issue by josephtkim** [maaya00/prj-rev-bwfs-dasmoto#5]
It is best to try to simplify the CSS code as much as possible for the shared properties. There are a few more shared properties that you can simplify like so

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}

#brush, #frame, #paint {
  color: blue;
}
```
